### ISSUE TITLE
似乎没法用了，无法镜像仓库

### ISSUE THREAD

**Issue by simon-sudo** [nulastudio/mclone#2]
错误提示如下：
```
git mclone https://github.com/Paxxs/Cluttered-bucket.git
无法镜像仓库：Post http://localhost:8080/clone: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.
```
是服务端出了问题还是我本机的8080被占用了？

我用了 `netstat`  命令看了一下，似乎**没有东西占用8080**

**Comment by liesauer** [comment]
你是自己编译的？不应该会访问`http://localhost:8080/clone`的，这是本地调试后台的时候才会用的，正式的话走的是`mclone.nulastudio.org`

**Comment by liesauer** [comment]
不好意思，我的锅，我不小心把调试的release上传了，我已经重新上传了一份，你重新安装即可。
