### ISSUE TITLE
mclone 不能够被使用

### ISSUE THREAD

**Issue by DullCat-c** [nulastudio/mclone#3]
PS C:\Users\DullCat> git mclone 'https://github.com/stimulusjs/stimulus-starter.git'
C:\\Users\\DullCat\\AppData\\Roaming\\mclone\\mclone.exe: C:UsersDullCatAppDataRoamingmclonemclone.exe: command not found
fatal: While expanding alias 'mclone': 'C:\\Users\\DullCat\\AppData\\Roaming\\mclone\\mclone.exe': No such file or directory

**Comment by liesauer** [comment]
不加单引号呢，我大概看看是命令行参数解析问题还是安装的问题。

**Comment by liesauer** [comment]
另外可以试一下重装。

**Comment by liesauer** [comment]
暂时关闭，如还有问题再重新打开。
